version: "3"
services:
  web:
    image: 192.168.99.100:55000/ftactivity/ui:ci-${UI_BUILD_NUMBER-1}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "3003:3003"
    networks:
      - webnet
    environment:
      - TEAMCITY_PROJECT_NAME	  
networks:
  webnet: